/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Artist = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
  'genre' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'venue' : IDL.Text,
  'city' : IDL.Text,
  'date' : IDL.Text,
  'artistId' : IDL.Text,
  'ticketUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RadarSummary = IDL.Record({
  'trackedArtistsCount' : IDL.Nat,
  'savedEventsCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEventToRadar' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getArtistById' : IDL.Func([IDL.Text], [IDL.Opt(Artist)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEventsByArtistId' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'getEventsByTrackedArtists' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getRadarEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getRadarSummary' : IDL.Func([], [RadarSummary], ['query']),
  'getTrackedArtists' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeEventFromRadar' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedArtists' : IDL.Func([IDL.Vec(Artist)], [], []),
  'seedEvents' : IDL.Func([IDL.Vec(Event)], [], []),
  'toggleTrackArtist' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Artist = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
    'genre' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'venue' : IDL.Text,
    'city' : IDL.Text,
    'date' : IDL.Text,
    'artistId' : IDL.Text,
    'ticketUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RadarSummary = IDL.Record({
    'trackedArtistsCount' : IDL.Nat,
    'savedEventsCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEventToRadar' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getArtistById' : IDL.Func([IDL.Text], [IDL.Opt(Artist)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEventsByArtistId' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'getEventsByTrackedArtists' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getRadarEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getRadarSummary' : IDL.Func([], [RadarSummary], ['query']),
    'getTrackedArtists' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeEventFromRadar' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedArtists' : IDL.Func([IDL.Vec(Artist)], [], []),
    'seedEvents' : IDL.Func([IDL.Vec(Event)], [], []),
    'toggleTrackArtist' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };