/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artist {
  'id' : string,
  'bio' : string,
  'name' : string,
  'imageUrl' : string,
  'genre' : string,
}
export interface Event {
  'id' : string,
  'title' : string,
  'source' : string,
  'venue' : string,
  'city' : string,
  'date' : string,
  'artistId' : string,
  'ticketUrl' : string,
}
export interface RadarSummary {
  'trackedArtistsCount' : bigint,
  'savedEventsCount' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEventToRadar' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllArtists' : ActorMethod<[], Array<Artist>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getArtistById' : ActorMethod<[string], [] | [Artist]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEventsByArtistId' : ActorMethod<[string], Array<Event>>,
  'getEventsByTrackedArtists' : ActorMethod<[], Array<Event>>,
  'getRadarEvents' : ActorMethod<[], Array<Event>>,
  'getRadarSummary' : ActorMethod<[], RadarSummary>,
  'getTrackedArtists' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeEventFromRadar' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedArtists' : ActorMethod<[Array<Artist>], undefined>,
  'seedEvents' : ActorMethod<[Array<Event>], undefined>,
  'toggleTrackArtist' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];